---
title: "flat_toolboxojdp.Rmd for working package"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- 
Run this 'development' chunk

Store every call to library() that you need to run chunks line by line, as in a classical Rmd for analysis
-->

```{r development, include=FALSE}
library(testthat)
```

<!--
# Description of your package

This will fill the description of your package.
Fill and run the content of this chunk, before anything else. 

Note: when you will use other flat templates, this part will be in a separate file. Do not be surprised!
--> 

```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Title = "plusieurs fonctions utiles au quotidien",
    Description = "A Set of tools to understand packages structure. Use Rmarkdown First method to build a package from a defined template. Start your package with documentation. Everything can be set from a Rmarkdown file in your project.",
    `Authors@R` = c(
      person("Ombeline", "JDP", email = "ombeline13@hotmail.Fr", role = c("aut", "cre"), comment = c(ORCID = "0000-0000-0000-0000"))
    )
  )
)
# Define License with use_*_license()
usethis::use_mit_license("OmbelineJD")
```

# Add one to any value

This is the first tool of our wonderful package. 
You can add `1` to any `value` using function `add_one()`.

<!-- 
This first section shows:

- the three parts necessary for a package: 'function', 'examples' and 'tests'.  
  + Note that the three following chunks have names accordingly.

-->
```{r function-get-one-file, echo=TRUE}
#' Add one to any value
#' 
#' @param file A character string specifying the file name
#' @import data.frame 
#' @return A data frame with file name and size
#' @export

get_one_file_size <- function(file = "analyse_facto.Rmd") {
  if (!file.exists(file)) {
    stop("Le fichier n'existe pas.")
  }
  
  file_size <- file.size(file)
  df <- data.frame(
    nom_fichier = file,
    taille_fichier = file_size
  )
  
  return(df)
}


```

<!--
Here is an example on how to use the function.
This should be a reproducible and working example
-->

```{r examples-get_one_file}
get_one_file_size("analyse_facto.Rmd")
```

<!--
Here are some unit tests to verify the function works as expected.
-->

```{r tests-get_one_file}


test_that("get_one_file_size works", {
  file.create("test_file.txt")  
  expect_true(file.exists("test_file.txt"))
  
  file_size <- file.size("test_file.txt")
  
  result <- get_one_file_size("test_file.txt")
  expect_equal(result$nom_fichier, "test_file.txt")
  expect_equal(result$taille_fichier, file_size)
  
  file.remove("test_file.txt")
  
  expect_error(get_one_file_size("non_existent_file.txt"), "Le fichier n'existe pas.")
})
```

That's it ! This the end of the documented story of our package. All components are there.

<!-- 
# Inflate your package

You're one inflate from paper to box.
Build your package from this very Rmd using `fusen::inflate()` 
-->


```{r development-inflate, eval=FALSE}
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_toolboxojdp.Rmd")
```

<!-- 
- Verify your `"DESCRIPTION"` file has been updated
- Verify your function is in `"R/"` directory
- Verify your test is in `"tests/testthat/"` directory
- Verify this Rmd appears in `"vignettes/"` directory 
-->
